### ISSUE TITLE
ElasticsearchException with LDAP authentication 

### ISSUE THREAD

**Issue by toto23** [floragunncom/search-guard#206]
Hello,

### Here is my environnent :

* Search Guard 2.3.3. 5 and Elasticsearch 2.3.3
* JVM 1.8.0_91 and RHEL 7.2 (Maipo)
* 9 ES Nodes

### Description of the bug :

When using LDAP authentication, i got an exception when i request ES with data spread on another nodes. For example, from a none master node :

**curl -k -u 'user:password' -XGET 'http://slbafreedes02.fr.intranet:9203/_cluster/health' --verbose** 
_[2016-09-13 14:42:49,261][WARN ][rest.suppressed          ] /_cluster/health Params: {}
**RemoteTransportException[[slbafreedes01-bobek][100.78.65.49:9301][cluster:monitor/health]]; nested: ElasticsearchException[java.io.InvalidClassException: Unauthorized deserialization attempt; org.ldaptive.SearchEntry]; nested: NotSerializableExceptionWrapper[invalid_class_exception: Unauthorized deserialization attempt; org.ldaptive.SearchEntry];**
Caused by: ElasticsearchException[java.io.InvalidClassException: Unauthorized deserialization attempt; org.ldaptive.SearchEntry]; nested: NotSerializableExceptionWrapper[invalid_class_exception: Unauthorized deserialization attempt; org.ldaptive.SearchEntry];
        at com.floragunn.searchguard.support.Base64Helper.deserializeObject(Base64Helper.java:74)
        at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:228)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:132)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245)
        at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:62)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
        at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:50)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
**Caused by: NotSerializableExceptionWrapper[invalid_class_exception: Unauthorized deserialization attempt; org.ldaptive.SearchEntry]**
        at com.floragunn.searchguard.support.Base64Helper$SafeObjectInputStream.resolveClass(Base64Helper.java:118)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at java.util.HashSet.readObject(HashSet.java:333)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at com.floragunn.searchguard.support.Base64Helper.deserializeObject(Base64Helper.java:72)
        ... 39 more_

On the SG auditlog index, we can see this exception marked as an SSL/certificate issue :
_ _type	  					auditlog
**audit_category	  			SSL_EXCEPTION
audit_details	  			ElasticsearchException[java.io.InvalidClassException: Unauthorized deserialization attempt; org.ldaptive.SearchEntry]; nested: InvalidClassException[Unauthorized deserialization attempt; org.ldaptive.SearchEntry];**
audit_principal	  			CN=slbafreedes02-junga,OU=xxxx Grid,O=xxxx,DC=xxxx,DC=xxxx
audit_reason	  			cluster:monitor/health
audit_request_class	  		class org.elasticsearch.action.admin.cluster.health.ClusterHealthRequest
audit_request_context	  	[_sg_ssl_transport_peer_certificates=>[Ljava.security.cert.X509Certificate;@18913e59, _sg_ssl_transport_protocol=>TLSv1.2, _sg_ssl_transport_cipher=>TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, _sg_channel_type=>netty, _sg_ssl_transport_intercluster_request=>true, _sg_ssl_transport_principal=>CN=slbafreedes02-junga,OU=xxxx Grid,O=xxxx,DC=xxxx,DC=xxxx]
audit_request_headers	  	[_sg_remote_address_header, _sg_user_header]_

I noticed this exception does not appear when the data is available on the node i request. For example, on a master node, this works :
**curl -k -u 'user:password' -XGET 'http://slbafreedes01.fr.intranet:9201/_cluster/health' --verbose** 

It seems to be a authentication issue between nodes but i don't have this problem using the basic or kerberos authentication.

Any idea on this ?

**Comment by floragunncom** [comment]
Should be fixed in this snapshot version: https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-2/2.3.3.6-SNAPSHOT/search-guard-2-2.3.3.6-20160913.200043-2.zip

Can you test/confirm it?

**Comment by floragunncom** [comment]
Please be aware that the LDAP component is not free software and you have to obtain a license for it when used in production. See https://floragunn.com/searchguard/searchguard-license-support/

**Comment by toto23** [comment]
We are in touch with Jochen Kressin for the license.

About the fix you gave me, i still have the issue but with another class this time:

_Caused by: NotSerializableExceptionWrapper[invalid_class_exception: Unauthorized deserialization attempt; **org.ldaptive.LdapEntry**]_

**Comment by floragunncom** [comment]
Sorry, this should work: https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-2/2.3.3.6-SNAPSHOT/search-guard-2-2.3.3.6-20160914.170619-3.zip

**Comment by toto23** [comment]
The fix works ! 
I will continue my tests.
Many thanks.
