### ISSUE TITLE
DLS blocking indices list in kibana

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#226]
With the latest releases ES 2.4.1 and SG 2.4.1.7 when I include the DLS line it gives an infinite problem with kibana and needing a default index even after it's set. Toggling that line fixes the issue, but I would like to use that jar.

<pre>
sg_public:
  cluster:
    - CLUSTER_MONITOR
    - MONITOR
  indices:
    '*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query*
        - indices:admin/get*
    'elastalert':
      '*':
        - ALL
    '?kibana':
      '*':
        - indices:*
    '/^\w+-\S*/':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
        - indices:admin/validate/query*
        - indices:admin/get*
      _dls_: '{ "term" : {"tags" : "devlogs" } }'
</pre>

**Comment by floragunncom** [comment]
What you mean by "use that jar"?

**Comment by djtecha** [comment]
I mean I have a license to use the dlsfls jar and using this version prevents me from doing so as my users are then blocked from listing indices. Once can type in the index name and it'll pop up with the fields, but you just can't save it as a default index.

**Comment by floragunncom** [comment]
Working on that ...

**Comment by floragunncom** [comment]
this should be fixed now with Search Guard v9 and the latest DLS/FLS jar.

**Comment by floragunncom** [comment]
does it work with the newest release(s)?

**Comment by djtecha** [comment]
Still having issues, getting:

Courier Fetch Error: unhandled courier request error: [class_cast_exception] null

This is resolved if I once again disable the _dls_ line

**Comment by floragunncom** [comment]
you need to test with search-guard-2-2.4.1.9 and dls module 2.4-5

**Comment by djtecha** [comment]
I'll try that, is search-guard-2-2.4.1.9 the latest then? The home page here says 2.4.1.7

**Comment by floragunncom** [comment]
https://github.com/floragunncom/search-guard/wiki

**Comment by djtecha** [comment]
Ahh need to bookmark that page :) Anyway, this appears to be working perfectly, thank you!

**Comment by floragunncom** [comment]
:-)
