### ISSUE TITLE
no match kibanaserver* in [IndexType [index=.kibana, type=config]]

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#252]
Hello,

I've installed ElasticSearch 5.0.2, Kibana 5.0.2, and SearchGuard 5:5.0.2-8.
LogStash is able to push the data to ElasticSearch.

When I try to access ElasticSearch using Kibana I am getting "{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}" error.

Log file and configuration files are attached.

Thanks,
Armenak
[kibana.yml.txt](https://github.com/floragunncom/search-guard/files/648007/kibana.yml.txt)
[elasticsearch.yml.txt](https://github.com/floragunncom/search-guard/files/648008/elasticsearch.yml.txt)
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/648009/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/648010/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/648011/sg_internal_users.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/648012/sg_roles_mapping.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/648013/sg_roles.yml.txt)

**Comment by floragunncom** [comment]
can you provide the elasticsearch logfile on DEBUG level?

**Comment by armenak** [comment]
Sorry, forgot to attache the log file. Please see below.

[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/650801/elasticsearch.log.txt)

**Comment by floragunncom** [comment]
root cause seems to be this https://github.com/elastic/kibana/pull/9214 - we are investigating this

**Comment by floragunncom** [comment]
This issue does also apply to Kibana 5.1.1

**Comment by floragunncom** [comment]
Install [search-guard-kibana-plugin-5.0.2.zip](https://github.com/floragunncom/search-guard/files/653326/search-guard-kibana-plugin-5.0.2.zip) and point your browser to http(s)://localhost:5601/login (or wherever your kibana lives)

**Comment by floragunncom** [comment]
BTW: We start working on a more advanced Kibana 5 plugin for Search Guard , but the above mentioned one should work until the other one is finished.

**Comment by floragunncom** [comment]
related https://github.com/elastic/kibana/issues/9442

**Comment by armenak** [comment]
How to install search-guard-kibana-plugin? More information would be greatly appreciated. And how this plugin is going to resolve the issue? Please elaborate.

**Comment by armenak** [comment]
By just guessing, installed the plugin under /usr/share/elasticsearch/plugins. Restarted ElasticSearch and see the following errors:

java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [search-guard-kibana-plugin]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:373) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:143) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.main(Command.java:62) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.0.2.jar:5.0.2]
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/search-guard-kibana-plugin/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_111]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_111]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_111]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_111]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:370) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 13 more
[2016-12-17T21:57:02,038][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [search-guard-kibana-plugin]. Was the plugin built before 2.0?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.0.2.jar:5.0.2]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [search-guard-kibana-plugin]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:373) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:143) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 6 more
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/search-guard-kibana-plugin/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_111]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_111]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_111]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_111]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:370) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:143) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 6 more

**Comment by floragunncom** [comment]
It's a plugin for kibana, so you need to install it into kibana (not elasticsearch).
See https://www.elastic.co/guide/en/kibana/current/kibana-plugins.html

**Comment by armenak** [comment]
I've installed this plugin in Kibana using the following command:
bin/kibana-plugin install
https://github.com/floragunncom/search-guard/files/653326/search-guard-kibana-plugin-5.0.2.zip
and received "Plugin installation complete" message.

After that I restarted Kibana.

Now I am getting error {"statusCode":404,"error":"Not Found"} when I
attempt to access http://<url>:5601/login

In Kibana log file I see the following:
Dec 19 21:19:30 <url> kibana[8053]:
{"type":"response","@timestamp":"2016-12-20T05:19:30Z","tags":[],"pid":8053,"method":"get","statusCode":404,"req":{"url":"/login","method":"get","headers":{"host":"<url>:5601","user-agent":"Mozilla/5.0
(Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101
Firefox/50.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip,
deflate","dnt":"1","connection":"keep-alive","upgrade-insecure-requests":"1","cache-control":"max-age=0"},"remoteAddress":"137.82.124.106","userAgent":"137.82.124.106"},"res":{"statusCode":404,"responseTime":6,"contentLength":9},"message":"GET
/login 404 6ms - 9.0B"}

Any idea why it is happening?

**Comment by floragunncom** [comment]
Can you try this one [searchguard-5.0.2.zip](https://github.com/floragunncom/search-guard/files/666295/searchguard-5.0.2.zip) ?

**Comment by Orsek123** [comment]
Hello, I have same problem as armenak. I try install searchguard-5.0.2.zip. The kibana writes error after restart. 

pro 22 12:59:07 dpl-dev-logstash kibana[18243]: {"type":"log","@timestamp":"2016-12-22T11:59:07Z","tags":["fatal"],"pid":18243,"level":"fatal","message":"++...ication no
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: FATAL { Error: +++ Search Guard authentication not available +++
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at ScopedPlugin.init [as externalInit] (/usr/share/kibana/plugins/searchguard/index.js:59:23)
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at ScopedPlugin.tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at Promise.attempt.Promise.try (/usr/share/kibana/node_modules/bluebird/js/main/method.js:30:24)
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at /usr/share/kibana/src/server/plugins/plugin.js:160:44
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at undefined.next (native)
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at step (/usr/share/kibana/src/server/plugins/plugin.js:11:273)
pro 22 12:59:07 dpl-dev-logstash kibana[18243]: at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by floragunncom** [comment]
We're releasing an alpha version of the plugin today, please stay tuned, we've fixed a couple of issues. Regarding your error, most likely you're missing the encryption key for the auth cookie in elasticsearch.yml:

searchguard.cookie.password: "<key>"

The key must be at least 32 characters.

**Comment by jochenkressin** [comment]
In Kibana 5.0.2 and above HTTP Basic Authentication is broken. We've just released a Kibana plugin which adds login/logout functionality and makes Kibana compatible with Search Guard again. It's currently in alpha, but if you want to give it a try, you can find the code and the alpha releases here:

https://github.com/floragunncom/search-guard-kibana-plugin 

Any feedback is much appreciated!

**Comment by matejzero** [comment]
I already replied in Google groups but in case someone missed it, I can confirm it's working on latest Kibana. I've tried with http basic auth and LDAP auth.

**Comment by armenak** [comment]
@matejzero can you please share your config files? I am still having the same problems.

**Comment by matejzero** [comment]
Sure:) I'll post an example for one of the SG default users.

sg_config.yml
```yaml
searchguard:
  dynamic:
    authc:
      basic_internal_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
```

sg_internal_users.yml
```yaml
readall:
  hash: $2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2
```

sg_roles_mapping.yml
```yaml
sg_all_access:
  users:
    - readall
```

sg_roles.yml
```yaml
sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'
```

After this is setup, run sgadmin.sh to apply changes and then first try to login directly to ES, just so we are sure SG is working as it should: `curl -u username:password http://es-node-hostname:9200/`.  You can also check if the user gets the right role: `curl -u username:password http://es-node-hostname:9200/_searchguard/api/user/` if you have the management REST API module installed.

If that is successful, move to Kibana. Go to Kibana's URL, without `/login/` in the end, just hostname and port eg. http://kibana-host.example.org:5601.

**Comment by floragunncom** [comment]
@Orsek123 does work https://github.com/floragunncom/search-guard-kibana-plugin for you?
@armenak omit the `/login` part in the url (as already mentioned by @matejzero)

**Comment by Orsek123** [comment]
Yeees! Thanks.

**Comment by armenak** [comment]
Not yet. I was on vacation. Will verify today or tomorrow.

**Comment by floragunncom** [comment]
@armenak ping

**Comment by armenak** [comment]
Sorry for the delay. Please give me one more day.

**Comment by armenak** [comment]
Unfortunately, I am still having same issues with Kibana. In Kibana I see the following error:
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

I noticed a warning in Kibana log:
kibana[27071]: {"type":"log","@timestamp":"2017-01-05T05:08:42Z","tags":["warning","config"],"pid":27071,"key":"searchguard","val":{},"message":"Settings for \"searchguard\" were not applied, check for spelling errors and ensure the plugin is loaded."}

The only change I made in kibana.yml was searchguard cookie password:
searchguard.cookie.password: "8PWmmA2dkNRRupuHmqAFjp9FnUVnFM7Vm"

Relevant portion of ElasticSearch log and config files are attached. 

ES version is 5.1
Java version is 1.8.0_11
SearchGuard version is 5-5.1.1-9
Kibana SearchGuard plugin version is searchguard-kibana-alpha-5.1.1

LogStash is working well. Authentication using other users such as "admin" and "readall" via curl is working too.

Any ideas?

[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/686472/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/686473/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/686475/sg_internal_users.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/686474/sg_roles_mapping.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/686476/sg_roles.yml.txt)
[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/686477/elasticsearch.log.txt)

**Comment by floragunncom** [comment]
@Orsek123 @matejzero do you also see this warning?

kibana[27071]: {"type":"log","@timestamp":"2017-01-05T05:08:42Z","tags":["warning","config"],"pid":27071,"key":"searchguard","val":{},"message":"Settings for "searchguard" were not applied, check for spelling errors and ensure the plugin is loaded."}

**Comment by matejzero** [comment]
No, my start procedure is nice and smooth.

```
Jan 05 09:49:05 host.example.org systemd[1]: Starting Kibana...
Jan 05 09:49:07 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:07Z","tags":["status","plugin:kibana@5.1.1","info"],"pid":2634,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:elasticsearch@5.1.1","info"],"pid":2634,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:searchguard@5.1.1","info"],"pid":2634,"state":"yellow","message":"Status changed from uninitialized to yellow - Initialising Search Guard authentication plugin.","prevState":"uninitialized","prevMsg":"uninitialized"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:searchguard@5.1.1","info"],"pid":2634,"state":"green","message":"Status changed from yellow to green - Search Guard access control initialised.","prevState":"yellow","prevMsg":"Initialising Search Guard authentication plugin."}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:console@5.1.1","info"],"pid":2634,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:timelion@5.1.1","info"],"pid":2634,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","plugin:elasticsearch@5.1.1","info"],"pid":2634,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["listening","info"],"pid":2634,"message":"Server running at https://kibana.example.org:5601"}
Jan 05 09:49:08 host.example.org kibana[2634]: {"type":"log","@timestamp":"2017-01-05T08:49:08Z","tags":["status","ui settings","info"],"pid":2634,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
```

**Comment by Orsek123** [comment]
No. Everything is ok.

**Comment by floragunncom** [comment]
@armenak Probably an error in the kibana config for the plugin: "Settings for "searchguard" were not applied, check for spelling errors and ensure the plugin is loaded." Can you check for correct spelling of the Search Guard config keys or post your kibana.yml?

**Comment by armenak** [comment]
@floragunncom kibana.yml is attached. Thank you for looking into it.
[kibana.yml.txt](https://github.com/floragunncom/search-guard/files/688568/kibana.yml.txt)

**Comment by armenak** [comment]
@floragunncom ping

**Comment by floragunncom** [comment]
@armenak I suggest that you try to install Kibana from a fresh download and then install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.1.1-alpha/searchguard-kibana-alpha-5.1.1.zip again.

**Comment by armenak** [comment]
After re-installing Kibana and SearchGuard plugin, everything works just fine. Thank you!
