### ISSUE TITLE
DLS is not working

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#277]
Environment: Java 1.8, ElasticSearch  5.1.1, SearchGuard 5.1.1, SearchGuard plugin for Kibana 5.1.1.

In sg_role.yml there is a definition of a new role:
<pre>
sg_as:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - KIBANA_USER
      _dls_: '{"term" : {"_type" : "syslog"}}'
    '?kibana':
      '*':
        - KIBANA_SERVER
</pre>
My understanding is that in Kibana I should see only log entries with type "syslog", however, I see log entries with "syslog" and "audit" types. 

Am I doing something wrong?

Attaching the configuration files.
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/707316/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/707319/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/707317/sg_internal_users.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/707318/sg_roles_mapping.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/707320/sg_roles.yml.txt)

Relevant part of log file is below.
<pre>
[root@event-apptst01 elasticsearch]# tail -f elasticsearch.log  | grep audit
[2017-01-15T21:34:20,425][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolved [logstash-*] to [logstash-audit-2017.01.16, logstash-syslog-2017.01.16]
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator] requested resolved indextypes: [IndexType [index=logstash-audit-2017.01.16, type=*], IndexType [index=logstash-syslog-2017.01.16, type=*]]
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator]   Wildcard match for logstash-*: [logstash-audit-2017.01.16, logstash-syslog-2017.01.16]
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator]     removed logstash-audit-2017.01.16*
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator] Aliases for logstash-audit-2017.01.16: []
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator] Aliases for logstash-audit-2017.01.16: []
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator] requestedResolvedIndexTypes '[IndexType [index=logstash-audit-2017.01.16, type=*], IndexType [index=logstash-syslog-2017.01.16, type=*]]'
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator]     no match armenak* in [IndexType [index=logstash-syslog-2017.01.16, type=*], IndexType [index=logstash-audit-2017.01.16, type=*]]
[2017-01-15T21:34:20,426][DEBUG][c.f.s.c.PrivilegesEvaluator] For index armenak remaining requested indextype: [IndexType [index=logstash-syslog-2017.01.16, type=*], IndexType [index=logstash-audit-2017.01.16, type=*]]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolve [logstash-audit-2017.01.16] from class org.elasticsearch.action.search.SearchRequest
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] raw indices [logstash-audit-2017.01.16]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolved [logstash-audit-2017.01.16] to [logstash-audit-2017.01.16]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] requested resolved indextypes: [IndexType [index=logstash-audit-2017.01.16, type=*]]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolve [logstash-audit-2017.01.16] from class org.elasticsearch.action.search.SearchRequest
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] raw indices [logstash-audit-2017.01.16]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolved [logstash-audit-2017.01.16] to [logstash-audit-2017.01.16]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] requested resolved indextypes: [IndexType [index=logstash-audit-2017.01.16, type=*]]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator]   Wildcard match for logstash-*: [logstash-audit-2017.01.16]
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator]     removed logstash-audit-2017.01.16*
[2017-01-15T21:34:20,532][DEBUG][c.f.s.c.PrivilegesEvaluator] Aliases for logstash-audit-2017.01.16: []
[2017-01-15T21:34:20,533][DEBUG][c.f.s.c.PrivilegesEvaluator] Aliases for logstash-audit-2017.01.16: []
[2017-01-15T21:34:20,533][DEBUG][c.f.s.c.PrivilegesEvaluator] requestedResolvedIndexTypes '[IndexType [index=logstash-audit-2017.01.16, type=*]]'
[2017-01-15T21:34:20,533][DEBUG][c.f.s.c.PrivilegesEvaluator]     no match armenak* in [IndexType [index=logstash-audit-2017.01.16, type=*]]
[2017-01-15T21:34:20,533][DEBUG][c.f.s.c.PrivilegesEvaluator] For index armenak remaining requested indextype: [IndexType [index=logstash-audit-2017.01.16, type=*]]
</pre>

**Comment by floragunncom** [comment]
Make sure you have the latest (5.1-5) DLS/FLS jar installed on all nodes (https://github.com/floragunncom/search-guard-module-dlsfls/wiki) and you have 5.1.1.10 as Search Guard versions. There were recently some issues with DLS/FLS but they are fixed in the most recent releases: https://github.com/floragunncom/search-guard/wiki/SecurityIssues

**Comment by armenak** [comment]
Still no luck. Seems to me that DLS query is simply being ignored.

I have installed SG 5.1.1-10 and 5.1-5 DLS/FLS plugin (see the screenshot)
![plugin](https://cloud.githubusercontent.com/assets/3421052/22052061/85a8d544-dcfc-11e6-8c18-3f5e3fbcc68e.png)

The log and config files are attached.
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/713099/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/713102/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/713103/sg_internal_users.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/713100/sg_roles_mapping.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/713101/sg_roles.yml.txt)

[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/713105/elasticsearch.log.txt)

**Comment by armenak** [comment]
Thank you for your help. Please close this issue. DLS is working. I will create a new one for FLS. It seems to me that the combination of DLS and FLS is not working yet.
