### ISSUE TITLE
Index patterns are set for all tenants in Kibana Multitenancy 6.1.1

### ISSUE THREAD

**Issue by CharlotteEGM** [floragunncom/search-guard#444]
Hi,

I am running search guard 20.1 on elasticsearch/kibana 6.1.1

I want to set up an index pattern A  for tenant A and an index pattern B for tenant B.
But then i can find index pattern A and B in both tenants. When i set up index pattern A in A, i find it in all other tenant.

Any idea on the issue here ? 

Thanks

**Comment by floragunncom** [comment]
This is a bug in the MT / KI module and will be fixed with the next release, scheduled for next week.

**Comment by jochenkressin** [comment]
This has been fixed with the Search Guard and Kibana plugin releases today. You need to upgrade to:

* [Search Guard 6.x-21.0](http://docs.search-guard.com/latest/changelog-6-x-21)
* [Kibana Plugin 6.x-10](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22)

**Comment by CharlotteEGM** [comment]
For me it still doesn't work with the new upgrade. I have upgraded to kibana 6.1.2 with searcg guard 21.0 and kibana plugin 6.1.2-10.

**Comment by jochenkressin** [comment]
Hm, somehow this can't be ;) since the complete code that was responsible for copying values between tenants has been removed. How can I reproduce this?

**Comment by CharlotteEGM** [comment]
I don't know...I'm using this docker that i have cloned for elasticsearch : [](https://github.com/khezen/docker-elasticsearch )
And this docker for Kibana : [](https://github.com/khezen/docker-elasticsearch)

I have just changed the version numbers in the dockerfiles. 
- elasticsearch version : 6.1.2
- searchguard version : 21.0
- kibana version : 6.1.2
- searchguard version (for kibana): 6.1.2-10

Maybe i am missing another config change ? Can I check somewhere the actual version of searchguard launched ? I can see in the logs of elasticsearch or kibana that it is really 6.1.2, but i don't see the version of searchguard

**Comment by jochenkressin** [comment]
You can visit this endpoint:

/_searchguard/license

Besides license infos this will also print the version numbers of the installed modules. Can you post it here please?

Also, if I understand correctly, steps to reproduce are:

- log in to Kibana
- switch to a tenant
- create index pattern
- switch to another tenant

Result: index pattern is present also in second tenant

Correct?

**Comment by CharlotteEGM** [comment]
```

sg_license |  
-- | --
uid | "00000000-0000-0000-0000-000000000000"
type | "TRIAL"
issue_date | "2018-01-26"
expiry_date | "2018-03-29"
issued_to | "The world"
issuer | "floragunn GmbH"
start_date | "2018-01-26"
major_version | 6
cluster_name | "*"
msgs | []
expiry_in_days | 47
is_expired | false
is_valid | true
action | ""
prod_usage | "Yes, one cluster with all commercial features and unlimited nodes per cluster."
license_required | true
allowed_node_count_per_cluster | "unlimited"
modules |  
AUDITLOG |  
default_implementation | "com.floragunn.searchguard.auditlog.impl.AuditLogImpl"
gitsha1 | "4c2d5d34976510c70c82ffbbaeec79f8d64ebf43"
buildTime | "2018-02-05T12:37:00Z"
is_enterprise | "true"
actual_implementation | "com.floragunn.searchguard.auditlog.impl.AuditLogImpl"
description | "Audit Logging"
type | "AUDITLOG"
version | "6.1.2-20.1"
INTERNAL_USERS_AUTHENTICATION_BACKEND |  
default_implementation | "com.floragunn.searchguard.auth.internal.InternalAuthenticationBackend"
gitsha1 | "a66a990971337f625e7ac99deeda5fcca32299a6"
buildTime | "2018-02-06T13:10:52Z"
is_enterprise | "false"
actual_implementation | "com.floragunn.searchguard.auth.internal.InternalAuthenticationBackend"
description | "Internal users authorization backend"
type | "INTERNAL_USERS_AUTHENTICATION_BACKEND"
version | "6.1.2-21.0"
REST_MANAGEMENT_API |  
default_implementation | "com.floragunn.searchguard.dlic.rest.api.SearchGuardRestApiActions"
gitsha1 | "a0709cbd1e1d61107682162cf5ec3840553dcb4c"
buildTime | "2017-12-22T15:49:45Z"
is_enterprise | "true"
actual_implementation | "com.floragunn.searchguard.dlic.rest.api.SearchGuardRestApiActions"
description | "REST Management API"
type | "REST_MANAGEMENT_API"
version | "6.0-20.0"
HTTP_BASIC_AUTHENTICATOR |  
default_implementation | "com.floragunn.searchguard.http.HTTPBasicAuthenticator"
gitsha1 | "a66a990971337f625e7ac99deeda5fcca32299a6"
buildTime | "2018-02-06T13:10:52Z"
is_enterprise | "false"
actual_implementation | "com.floragunn.searchguard.http.HTTPBasicAuthenticator"
description | "HTTP Basic Authenticator"
type | "HTTP_BASIC_AUTHENTICATOR"
version | "6.1.2-21.0"
DLSFLS |  
default_implementation | "com.floragunn.searchguard.configuration.SearchGuardFlsDlsIndexSearcherWrapper"
gitsha1 | "b58d834423501292df9d6b976a168d5047607675"
buildTime | "2018-02-05T13:34:50Z"
is_enterprise | "true"
actual_implementation | "com.floragunn.searchguard.configuration.SearchGuardFlsDlsIndexSearcherWrapper"
description | "Document- and Field-Level Security"
type | "DLSFLS"
version | "6.0-20.1"
MULTITENANCY |  
default_implementation | "com.floragunn.searchguard.configuration.PrivilegesInterceptorImpl"
gitsha1 | "d9dae44e7d25f475792f553bdeeb4d125492d6cf"
buildTime | "2018-02-05T13:50:27Z"
is_enterprise | "true"
actual_implementation | "com.floragunn.searchguard.configuration.PrivilegesInterceptorImpl"
description | "Kibana Multitenancy"
type | "MULTITENANCY"
version | "6.0-21.0"
compatibility |  
modules_mismatch | false
```

Yes the step to reproduce are correct

**Comment by jochenkressin** [comment]
This is not an error in Search Guard. We used the the original repos you mentioned above and after configuring multi tenancy everything works as expected.

However, the Dockerfiles and the especially the SG configuration in this repo is not correct:

* Multi tenancy is not enabled in sg_config
* The Kibana server user that is configured in kibana.yml is not configured in sg_config
* There is only one Kibana role, usually you should use two, one for the Kibana serve user, one for regular Kibana users
* The permissions for the Kibana server user are not correct. They especially lack the  indices:admin/template* permission
* the "sgtenant" HTTP header is  not whitelisted in kibana.yml

After fixing all these configuration errors in the Dockerfile everything works as expected. If you need further assistance in settup up MT, please ask on the Google Groups: https://groups.google.com/forum/#!forum/search-guard

Closing, not a bug.
