### ISSUE TITLE
Kibana with SearchGuard keeps crashing

### ISSUE THREAD

**Issue by sg-beginner** [floragunncom/search-guard#535]
Hi there

Our Kibana of version 6.2.2 has installed SearchGuard plugin of related version. What we can see is that Kibana keeps crashing with the following error:

{"type":"error","@timestamp":"2018-08-04T10:42:20Z","tags":[],"pid":63049,"level":"error","error":{"message":"Uncaught error: Cannot read property 'split' of undefined","name":"TypeError","stack":"TypeError:                              Uncaught error: Cannot read property 'split' of undefined\n    at server.auth.test (/opt/kibana-6.2.2-linux-x86_64/plugins/searchguard/lib/hapi/auth.js:65:64)\n    at transfer (/opt/kibana-6.2.2-linux-x86_64/                             node_modules/hapi/lib/auth.js:92:16)\n    at Function.wrapped [as _next] (/opt/kibana-6.2.2-linux-x86_64/node_modules/hoek/lib/index.js:875:20)\n    at Function.internals.response (/opt/kibana-6.2.2-linux-x86                             _64/node_modules/hapi/lib/reply.js:138:14)\n    at reply (/opt/kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/reply.js:70:22)\n    at unauthenticated (/opt/kibana-6.2.2-linux-x86_64/plugins/searchguard/node_                             modules/hapi-auth-cookie/lib/index.js:169:28)\n    at validate (/opt/kibana-6.2.2-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:122:28)\n    at Object.authenticate (/opt/kibana-6                             .2.2-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:187:13)\n    at internals.Auth.test (/opt/kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/auth.js:96:22)\n    at Object.test (/                             opt/kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/plugin.js:65:64)\n    at Object.authenticate (/opt/kibana-6.2.2-linux-x86_64/plugins/searchguard/lib/hapi/auth.js:58:25)\n    at request._protect.run (/opt/                             kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/auth.js:324:34)\n    at internals.Protect.run (/opt/kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/protect.js:64:5)\n    at execute (/opt/kibana-6.2.2-linux-x8                             6_64/node_modules/hapi/lib/auth.js:320:30)\n    at authenticate (/opt/kibana-6.2.2-linux-x86_64/node_modules/hapi/lib/auth.js:306:21)\n    at internals.Auth._authenticate (/opt/kibana-6.2.2-linux-x86_64/node_                             modules/hapi/lib/auth.js:214:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/","path":"/","href":"/"},"message":                             "Uncaught error: Cannot read property 'split' of undefined"}

So far we were unable to identify the root cause of this.

**Comment by mgustafsson1** [comment]
Should be fixed with https://github.com/floragunncom/search-guard-kibana-plugin/pull/121

**Comment by floragunncom** [comment]
Will be released with v14, expected next week.

**Comment by floragunncom** [comment]
Fixed with Search Guard Plugin v14.

**Comment by tiagoReichert** [comment]
I'm still getting following error message on plugin v14:

`{"type":"error","@timestamp":"2018-09-10T17:00:49Z","tags":["warning","process"],"pid":16,"level":"error","error":{"message":"Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'split' of undefined","name":"UnhandledPromiseRejectionWarning","stack":"TypeError: Cannot read property 'split' of undefined\n    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:183:68\n    at next (native)\n    at step (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:191)\n    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:437\n    at /opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:23:99\n    at server.auth.test (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:160:17)\n    at transfer (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/auth.js:92:16)\n    at Function.wrapped (/opt/kibana-6.2.4-linux-x86_64/node_modules/hoek/lib/index.js:875:20)\n    at Function.internals.response (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/reply.js:138:14)\n    at reply (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/reply.js:70:22)\n    at unauthenticated (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:169:28)\n    at validate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:122:28)\n    at Object.authenticate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/node_modules/hapi-auth-cookie/lib/index.js:187:13)\n    at internals.Auth.test (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/auth.js:96:22)\n    at Object.test (/opt/kibana-6.2.4-linux-x86_64/node_modules/hapi/lib/plugin.js:65:64)\n    at Object.authenticate (/opt/kibana-6.2.4-linux-x86_64/plugins/searchguard/lib/auth/types/AuthType.js:160:34)"},"message":"Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'split' of undefined"}
`
